[build]
  publish = "dist"
  command = "npm run build"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  VITE_API_URL = "https://acadmate-backend-2025.onrender.com/api"
  VITE_ENVIRONMENT = "production"
  VITE_ENABLE_PERFORMANCE_MONITORING = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment-specific redirects for API calls
[[redirects]]
  from = "/api/*"
  to = "https://acadmate-backend-2025.onrender.com/api/:splat"
  status = 200
  force = false

# Prevent access to sensitive files
[[redirects]]
  from = "/.env*"
  to = "/404"
  status = 404

[[redirects]]
  from = "/config/*"
  to = "/404"
  status = 404